### ISSUE TITLE
ModuleNotFoundError: No module named 'absa_parser'

### ISSUE THREAD

**Issue by minionssso** [CCChenhao997/DualGCN-ABSA#10]
When I set 'parseadj=True', but I got a error about this, what should I do? Thanks!

`Traceback (most recent call last):
  File "/media/pwy/新加卷/Addie_zmy/DualGCN-ABSA/DualGCN/train.py", line 385, in <module>
    main()
  File "/media/pwy/新加卷/Addie_zmy/DualGCN-ABSA/DualGCN/train.py", line 381, in main
    ins = Instructor(opt)
  File "/media/pwy/新加卷/Addie_zmy/DualGCN-ABSA/DualGCN/train.py", line 77, in __init__
    trainset = SentenceDataset(opt.dataset_file['train'], tokenizer, opt=opt, vocab_help=vocab_help)
  File "/media/pwy/新加卷/Addie_zmy/DualGCN-ABSA/DualGCN/data_utils.py", line 194, in __init__
    from absa_parser import headparser
ModuleNotFoundError: No module named 'absa_parser'`

**Comment by minionssso** [comment]
路径问题，已解决
Path problem, resolved

**Comment by ldy0808** [comment]
您好请问是如何解决的呢

**Comment by KokiaY** [comment]
I know

**Comment by zihaowwng** [comment]
请问是如何解决的呢？尝试过各种路径问题解决方法最终还是没有解决这个问题。

**Comment by zihaowwng** [comment]
> 路径问题，已解决 Path problem, resolved
你好！请问是如何解决的呢？

**Comment by CCChenhao997** [comment]
统一回复一下，请在 DualGCN-ABSA-Main 目录下运行 sh DualGCN/run.sh

**Comment by chenmiaozi-maker** [comment]
> 请问是如何解决的呢？尝试过各种路径问题解决方法最终还是没有解决这个问题。

请问你解决这个问题了吗？我也是报这个错误：ModuleNotFoundError: No module named 'absa_parser'

**Comment by chenmiaozi-maker** [comment]
> 路径问题，已解决 Path problem, resolved

请问怎么解决的呢

**Comment by zgluck** [comment]
> 统一回复一下，请在 DualGCN-ABSA-Main 目录下运行 sh DualGCN/run.sh

这样也不行啊

**Comment by zgluck** [comment]
请问怎么解决的？

**Comment by sdwulxr** [comment]
> 统一回复一下，请在 DualGCN-ABSA-Main 目录下运行 sh DualGCN/run.sh

你好，请问你运行的时候是用的run.sh文件里面的参数还是代码中自带的参数啊，为什么我用了run.sh里面的参数运行出来的结果没有用代码中自带的参数运行出来的结果高呀？期待你的回复，谢谢！

**Comment by zgluck** [comment]
不好意思，我那时候没有运行出来。我就没再运行了。代码参数是可以调的。因为环境不同。最优解也不同。这个不用纠结。就用你运行结果好的那组参数就可以。



---Original---
From: ***@***.***&gt;
Date: Sat, Jul 20, 2024 15:02 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [CCChenhao997/DualGCN-ABSA] ModuleNotFoundError: No module named'absa_parser' (Issue #10)




  
统一回复一下，请在 DualGCN-ABSA-Main 目录下运行 sh DualGCN/run.sh
  
你好，请问你运行的时候是用的run.sh文件里面的参数还是代码中自带的参数啊，为什么我用了run.sh里面的参数运行出来的结果没有用代码中自带的参数运行出来的结果高呀？期待你的回复，谢谢！

**Comment by sdwulxr** [comment]
> 不好意思，我那时候没有运行出来。我就没再运行了。代码参数是可以调的。因为环境不同。最优解也不同。这个不用纠结。就用你运行结果好的那组参数就可以。
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Sat, Jul 20, 2024 15:02 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [CCChenhao997/DualGCN-ABSA] ModuleNotFoundError: No module named'absa_parser' (Issue #10) 统一回复一下，请在 DualGCN-ABSA-Main 目录下运行 sh DualGCN/run.sh 你好，请问你运行的时候是用的run.sh文件里面的参数还是代码中自带的参数啊，为什么我用了run.sh里面的参数运行出来的结果没有用代码中自带的参数运行出来的结果高呀？期待你的回复，谢谢！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

好的 ，谢谢！

**Comment by chenguang1870** [comment]
请问大家这个问题怎么解决的啊，搞了一整天了，求大佬赐教
